#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Install dependencies') {
            steps {
              withEnv(['LC_ALL=C']) {
                sh 'make install'
              }
            }
        }

        stage('Run unit tests') {
            steps {
                sh 'make test'
            }
        }

        stage('Build AMI') {
            steps {
                dir('/opt/packer/templates') {
                    sh 'packer build -only=amazon-ebs flask-app.json'
                }
            }
        }

        stage('Deploy AMI') {
            steps {
                dir('/opt/terraform/aws/flask-app') {
                    sh 'terraform init && terraform apply -auto-approve'
                }
            }
        }
    }
}
